/*
 * Resources.h
 *
 *  Created on: 30/05/2012
 *      Author: Gustavo
 */

#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <escort.service/NandFFS/NandFFS.h>

namespace trf {
namespace pontos12 {
namespace application {
namespace gui {

class Resources {
public:
	typedef enum{
		RECONHECENDO_USB = 0,
		DISPOSITIVO_INCOMPATIVEL = RECONHECENDO_USB + 2,
		FUNCAO_BLOQUEADA = DISPOSITIVO_INCOMPATIVEL + 2,
		AGUARDE = FUNCAO_BLOQUEADA + 2,
		COLOQUE_PENDRIVE,
		VERSAO = COLOQUE_PENDRIVE + 2,
		ROTEIROS,
		MENSAGENS,
		NUMERO_SERIE,
		PAINEL,
		AJUSTAR_PARTIDA,
		SENTIDO,
		IDA,
		VOLTA,
		IDENTIFICANDO,
		FALHA,
		SUCESSO,
		NOVA_CONFIG = SUCESSO + 2,
		AJUSTAR_RELOGIO,
		SELEC_REGIAO,
		CONFIGURACOES,
		IDENTIF_PAINEIS,
		COLETAR_DUMP,
		FORMAT_PENDRIVE,
		DOM_SEG_TER_QUA_QUI,
		SEX_SAB,
		MENSAGEM,
		SELECIONA_PAINEL,
		ROTEIRO,
		AUTOMATICO,
		PAINEIS = AUTOMATICO + 2,
		DESEJA_FORMATAR,
		ATUALIZANDO = DESEJA_FORMATAR + 2,
		REMOVA_PENDRIVE,
		RESETANDO,
		CARREGUE_CONFIG,
		APAGAR_ARQUIVOS = CARREGUE_CONFIG + 2,
		SINCRONIZANDO,
		PAINEL_NAO_DETECTADO,
		OPCOES_AVANCADAS = PAINEL_NAO_DETECTADO + 2,
		COLETANDO,
		COLETAR_LOG,
		PAINEL_COM_DEFEITO,
		SIM_NAO = PAINEL_COM_DEFEITO + 2,
		DESEJA_DESBLOQUEAR_FUNCAO,
		SENHA = DESEJA_DESBLOQUEAR_FUNCAO + 2,
		SENHA_INCORRETA,
		CONTROLADOR = SENHA_INCORRETA +2,
		TODOS_DISPOSITIVOS,
		TODOS_PAINEIS,
		SISTEMA_ARQUIVO_DEFEITUOSO,
		ACENDER_PAINEIS = SISTEMA_ARQUIVO_DEFEITUOSO + 2,
		SENHA_ANTI_FURTO_INCORRETA,
		SAIDA = SENHA_ANTI_FURTO_INCORRETA + 2,
		DOMINGO,
		SEGUNDA,
		TERCA,
		QUARTA,
		QUINTA,
		SEXTA,
		SABADO,
		CONFIG_FABRICA,
		FALHA_COMUNICACAO,
		NOVA_CONFIG_INVALIDA = FALHA_COMUNICACAO + 2,
		EMPARELHAMENTO_INCOMPATIVEL = NOVA_CONFIG_INVALIDA + 2,
		TEMPO_ACESO = EMPARELHAMENTO_INCOMPATIVEL + 2,
		TEMPO_APAGADO,
		INDEFINIDO,
		APP_NAO_DETECTADO,
		NENHUM_ARQUIVO = APP_NAO_DETECTADO + 2,
		MENSAGEM_SECUNDARIA,
		MENSAGEM_PRINCIPAL,
		NOMEIE_PASTA,
		TESTE_AUTOMATICO,
		LINHAS,
		COLUNAS,
		APAGADO,
		ACESO,
		TEXTO,
		DESLIGAR_TESTE,
		MODO_TESTE,
		APP,
		AJUSTAR_BRILHO,
		SELECIONAR_MOTORISTA,
		PROXIMA_PARADA,
		MENSAGEM_NSS,
		PAINEIS_TRAVADOS,
		DESTRAVAR_PAINEIS = PAINEIS_TRAVADOS + 2,
		ID_DESTRAVAMENTO,
		TESTE_TECLADO,
		TECLA_ROT_ESQ,
		TECLA_ROT_DIR,
		TECLA_IDA_VOLTA,
		TECLA_ALTERNA,
		TECLA_MSG_ESQ,
		TECLA_MSG_DIR,
		TECLA_SELEC_PAINEL,
		TECLA_AJUSTES_ESQ,
		TECLA_AJUSTES_DIR,
		COMECE_TESTE,
		PRESSIONE_OK,
		APP_MODO_DEMONSTRACAO,
		DESEJA_ATUALIZAR_FW
		//PROXIMO = DESEJA_ATUALIZAR + 2
	} Texto;

public:
	static void init(escort::service::NandFFS* fileSystem, char* idiomaPath);
	static char* getTexto(Texto texto);
	static void setIdiomaPath(char* idiomaPath);

private:
	static escort::service::NandFFS* fileSystem;
	static char idiomaPath[64];
	static char buffer[33];
};

}
}
}
}

#endif /* RESOURCES_H_ */
